kruize/kruize-ui

Dockerfile
README.md
deploy.sh
src/app/Analytics/SRE_Analytics/MonitoringTable.tsx
src/app/Analytics/SRE_Analytics/RecommendationTables.tsx
src/app/Analytics/SRE_Analytics/UsecaseSelection.tsx
src/app/HorizontalNav/HorizontalNav.tsx

This pr makes changes to the deploy script and docker file to incorporate 2 methods of running the ui locally and in a container.

Changes ip & port to service name

---

src/app/Analytics/SRE_Analytics/RecommendationTables.tsx

This pr fixes following minor issues in ui
1. Displaying recommendations for single time stamp
2. Fixing precision for cpu and memory data

Fixes single recommendation display

---

src/app/Analytics/SRE_Analytics/ReccomendationComponents/WorkloadDetails.tsx
src/app/Analytics/SRE_Analytics/RecommendationTables.tsx
src/app/Analytics/SRE_Analytics/SREAnalytics.tsx
src/app/Analytics/SRE_Analytics/UsecaseSelection.tsx

Replaces workload table with text data

---

src/app/Analytics/SRE_Analytics/RecommendationComponents/CostDetails.tsx
src/app/Analytics/SRE_Analytics/RecommendationComponents/PerfDetails.tsx
src/app/Analytics/SRE_Analytics/RecommendationComponents/PerfHistoricCharts.tsx
src/app/Analytics/SRE_Analytics/RecommendationComponents/TabSection.tsx
src/app/Analytics/SRE_Analytics/RecommendationTables.tsx

Adds performance charts, adds plus sign for delta values, sets copy icon in recommended code block in performance tab

Adds performance charts

---

src/app/CentralConfig.tsx
src/app/LocalMonitoring/ClusterDataTable.tsx
src/app/LocalMonitoring/ClusterGroupTables.tsx
src/app/LocalMonitoring/DatasourceTable.tsx
src/app/LocalMonitoring/ImportMeta.json
src/app/LocalMonitoring/LocalMonitoring.tsx
src/app/routes.tsx
tsconfig.json

This pr has changes corresponding to:

Kruize Local POC changes 

---

src/app/Analytics/LocalMonitoring/ClusterDataTable.tsx
src/app/Analytics/LocalMonitoring/ClusterGroupTables.tsx
src/app/Analytics/LocalMonitoring/CreateExperiment.tsx
src/app/Analytics/LocalMonitoring/DatasourceTable.tsx
src/app/Analytics/LocalMonitoring/GenerateJSON/CodeEditorWithActions.tsx
src/app/Analytics/LocalMonitoring/GenerateJSON/createExperimentYAML.tsx
src/app/Analytics/LocalMonitoring/LocalMonitoring.tsx
src/app/CentralConfig.tsx
src/app/GenerateYaml/CodeEditorWithActions.tsx
src/app/routes.tsx

This pr :
1. Displays the Container level details.
2. calls list exp api to check for existing experiments.
3. displays create Experiment code editor to create exp for selected container. 
4. call a post create exp api successfully.

Container details & Create exp api integration.

---

src/app/routes.tsx

[link ](https://www.loom.com/share/4b98b79d452943f5bcb10fe5c0cf4f70?sid=b42e9574-7056-4711-8fb5-f05c6807fd99) This is a video link of how the ui looks after changes made in this pr.
Solves jira 279

Adds 2 tabs on the side Datasource and experiment

---

src/app/Analytics/LocalMonitoring/ClusterDataTable.tsx
src/app/Analytics/LocalMonitoring/ClusterGroupTables.tsx
src/app/Analytics/LocalMonitoring/DatasourceTable.tsx
src/app/routes.tsx

Solves jira 275. This pr is on top of 177 pr, and would require 177 to get merged first. view attached below.

Restructure pages

---

src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/Monitoring.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/CostDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/WorkloadDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationTables.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/UsecaseSelection.tsx

This pr adds Experiment Usecase type value on the ui and the logical changes related to it. solves jira 319,

Adds support for Experiment Usecase Type 

---

src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/UsecaseSelection.tsx

This pr replaces generate recc api call with list recc api call
solves jira 276. This is built on top of PR 180, and needs 180 to be merged before this one.

Replaces Generate API call to List API call

---

src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/Monitoring.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/WorkloadDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/UsecaseSelection.tsx
src/app/routes.tsx

This pr contains changes suggested for Fuse tabs functionality ,
- merges the 2 Tabs exp and recommendations
- fixes the Recommendations button, refresh icon 
- and other minor issues faced while integration.
https://www.loom.com/share/42259f859be9499a96713128bcfd8fb9?sid=95ca3ed9-8893-41f4-a019-c60c25b3d984

Fuse tabs for Exp and Recommendations

---

src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/BoxPlot/BoxPlot.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/CostBoxPlotCharts.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/CostDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/PerfDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/TabSection.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationTables.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/UsecaseSelection.tsx

Adds box plot chart on top of the recent changes in mvp_demo. Fixes tooltip layout and display.

Box plot changes - Part 1

---

src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/CostBoxPlotCharts.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/PerfBoxPlotCharts.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/CostDetails.tsx
src/app/Analytics/RemoteMonitoring/RecommendationComponents/CostDetails.tsx
src/app/Analytics/RemoteMonitoring/RecommendationComponents/CostHistoricCharts.tsx
src/app/Analytics/RemoteMonitoring/RecommendationComponents/PerfDetails.tsx
src/app/Analytics/RemoteMonitoring/RecommendationComponents/PerfHistoricCharts.tsx

Fixes all possibilities causing _`_TypeError: Cannot read properties of undefined (reading 'amount')_`_ UI works fine after this change, displaying empty values instead of throwing empty ui page.

Fixes type error

---

src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/Monitoring.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/BoxPlot.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/wrapper.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/CostDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/PerfDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationTables.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/UsecaseSelection.tsx

Adds Notification at level 1, level 2

---

src/app/Analytics/LocalMonitoring/GenerateJSON/createExperimentYAML.tsx

Fix for create exp in local monitoring mode ui.

Fixes create exp yaml for local monitoring

---

src/app/Analytics/LocalMonitoring/DatasourceTable.tsx
src/app/Analytics/LocalMonitoring/LocalMonitoring.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/CostBoxPlotCharts.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/BoxPlots/PerfBoxPlotCharts.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/CostDetails.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/LinePlot/ChartDataPreparation.tsx
src/app/Analytics/LocalMonitoring/RecommendationsForLocalMonitoring/RemoteMonitoring/RecommendationComponents/PerfDetails.tsx

Fixes the following errors under no particular category
1. Display of variation( or delta) values not correct
2. TypeError: Cannot read properties of undefined (reading 'map'), listdatasources api
this pr is on top of other 2 bug fixes pr

Miscellaneous Bug fixes

---

Dockerfile
package.json

Update Dockerfile to build on node:22 version

Bump mvp_demo to UI Version 0.0.7

---

README.md

Adds steps on how user can use kind cluster when minikube is having issues, for ui debugging and development purposes.

updates readme to include kind

---

src/app/Analytics/LocalMonitoring/DatasourceTable.tsx
src/store/actions/DataSourceActionCreator.tsx

Fixes api code for issues in running bulk demo. Tested on kind

Fix api call for Bulk demo

---

src/app/Analytics/LocalMonitoring/ClusterDataTable.tsx
src/app/Analytics/LocalMonitoring/ClusterGroupTables.tsx
src/app/Analytics/LocalMonitoring/CreateBulkExperiment.tsx
src/app/Analytics/LocalMonitoring/CreateBulkExperiment/CodeEditorWithActions.tsx
src/app/Analytics/LocalMonitoring/CreateBulkExperiment/createBulkExperimentYAML.tsx
src/app/CentralConfig.tsx
src/app/routes.tsx

Integrated bulk api workflow on the ui, mvp level changes.

Integrates mvp level bulk api changes on the ui

---

src/app/Analytics/LocalMonitoring/GenerateJSON/CodeEditorWithActions.tsx

adds link on the create experiment alert to redirect users to the experiments page.
closes #223

Completes create experiment to view experiment flow

---

package-lock.json
package.json

Update mvp_demo to UI version 0.0.9

Update mvp_demo to UI version 0.0.9

---

package-lock.json
package.json
src/app/Analytics/LocalMonitoring/ClusterDataTable.tsx
src/app/Analytics/LocalMonitoring/ClusterGroupTables.tsx
src/app/Analytics/LocalMonitoring/CreateBulkExperiment.tsx
src/app/Analytics/LocalMonitoring/CreateBulkExperiment/CodeEditorWithActions.tsx
src/app/Analytics/LocalMonitoring/CreateBulkExperiment/createBulkExperimentYAML.tsx
src/app/Analytics/LocalMonitoring/GenerateJSON/CodeEditorWithActions.tsx
src/app/Analytics/LocalMonitoring/GenerateJSON/createExperimentYAML.tsx
src/app/CentralConfig.tsx
src/app/routes.tsx
src/store/actions/DataSourceActionCreator.tsx

Merge UI v0.0.9 changes to main

Merge mvp_demo 0.0.9 to main
